name: Test API 

on:
  push:
    branches:
      - main

jobs:
  test_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install python3

      - name: Install Flask
        run: |
          python3 -m pip install Flask
            
      - name: Execute app 
        run: |
          python3 api_calculadora.py &
          phython3 calculadora.py &
       
      - name: Test API
        run: |
          if curl -s http://localhost:5000/suma/7/10 | grep -q "17"; then
            echo "Suma correcta."
          else
            echo "Suma incorrecta."
            exit 1
          fi
           if curl -s http://localhost:5000/resta/10/7 | grep -q "3"; then
            echo "Resta correcta."
          else
            echo "Resta incorrecta."
            exit 1
          fi
           if curl -s http://localhost:5000/multiplica/7/10 | grep -q "70"; then
            echo "Multiplicacion correcta."
          else
            echo "Multiplicacion incorrecta."
            exit 1
          fi
           if curl -s http://localhost:5000/divideix/2/10 | grep -q "5"; then
            echo "Division correcta."
          else
            echo "Division incorrecta."
            exit 1
          fi

          
